import Head from 'next/head';

import { H1Tag } from './index.styles';
export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<title>hi</title>
			</Head>

			<H1Tag color="primary" fsize="large">
				hi
			</H1Tag>
			<div style={{ fontSize: '18px' }}>hi</div>
		</>
	);
}
